/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Type__4 = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Type__1 = IDL.Variant({
  'none' : IDL.Null,
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
});
export const Type__3 = IDL.Variant({
  'GST' : IDL.Null,
  'TDS' : IDL.Null,
  'ITNotice' : IDL.Null,
  'Accounts' : IDL.Null,
  'Audit' : IDL.Null,
  'Other' : IDL.Null,
  'FormFiling' : IDL.Null,
  'CACertificate' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : IDL.Nat32,
  'pan' : IDL.Opt(IDL.Text),
  'status' : Type__4,
  'subCategory' : IDL.Opt(IDL.Text),
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'recurring' : Type__1,
  'gstin' : IDL.Opt(IDL.Text),
  'taskCategory' : Type__3,
});
export const Time = IDL.Int;
export const ToDoItemCreate = IDL.Record({
  'title' : IDL.Text,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Type__2 = IDL.Variant({
  'pending' : IDL.Null,
  'hold' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'docsPending' : IDL.Null,
});
export const Type = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat32,
  'status' : Type__2,
  'title' : IDL.Text,
  'clientId' : IDL.Nat32,
  'paymentStatus' : Type,
  'subType' : IDL.Opt(IDL.Text),
  'completionDate' : IDL.Opt(Time),
  'assignedTo' : IDL.Principal,
  'clientName' : IDL.Text,
  'assignmentDate' : IDL.Opt(Time),
  'bill' : IDL.Opt(IDL.Text),
  'advanceReceived' : IDL.Opt(IDL.Nat),
  'createdAt' : Time,
  'recurring' : Type__1,
  'dueDate' : IDL.Opt(Time),
  'manualAssignmentDate' : IDL.Opt(Time),
  'taskType' : Type__3,
  'comment' : IDL.Opt(IDL.Text),
  'outstandingAmount' : IDL.Opt(IDL.Nat),
  'captains' : IDL.Vec(IDL.Principal),
  'assignedName' : IDL.Text,
});
export const TeamMemberData = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const ToDoAuthRequest = IDL.Record({
  'owner' : IDL.Principal,
  'todoId' : IDL.Nat32,
});
export const TaskFilter = IDL.Record({
  'status' : IDL.Opt(Type__2),
  'paymentStatus' : IDL.Opt(Type),
  'subType' : IDL.Opt(IDL.Text),
  'assigneeName' : IDL.Opt(IDL.Text),
  'searchTerm' : IDL.Opt(IDL.Text),
  'taskType' : IDL.Opt(Type__3),
  'comment' : IDL.Opt(IDL.Text),
});
export const DateSearchResult = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'date' : Time,
});
export const ToDoFilterType = IDL.Variant({
  'all' : IDL.Null,
  'today' : IDL.Null,
});
export const ToDoItemOwner = IDL.Principal;
export const ToDoItem = IDL.Record({
  'id' : IDL.Nat32,
  'title' : IDL.Text,
  'owner' : ToDoItemOwner,
  'modifiedAt' : Time,
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Opt(IDL.Text),
});
export const TeamMember = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const SortDirection = IDL.Variant({
  'asc' : IDL.Null,
  'desc' : IDL.Null,
});
export const DashboardTasksRequest = IDL.Record({
  'completionDateSortDirection' : SortDirection,
  'dueDateSortDirection' : SortDirection,
});
export const DashboardTasksResponse = IDL.Record({
  'completionDateSorted' : IDL.Vec(Task),
  'dueDateSorted' : IDL.Vec(Task),
});
export const DueDateCountResponse = IDL.Record({
  'dueTodayCount' : IDL.Nat,
  'dueTomorrowCount' : IDL.Nat,
  'customDateCount' : IDL.Nat,
  'anyDateCount' : IDL.Nat,
});
export const DueDateDayType = IDL.Variant({
  'dueTomorrow' : IDL.Null,
  'dueToday' : IDL.Null,
  'anyDate' : IDL.Null,
  'customDate' : Time,
});
export const DueDateTaskDetails = IDL.Record({
  'status' : Type__2,
  'assignee' : IDL.Text,
  'paymentStatus' : Type,
  'clientName' : IDL.Text,
  'dueDate' : IDL.Opt(Time),
  'taskTitle' : IDL.Text,
  'comments' : IDL.Opt(IDL.Text),
});
export const DueDateModalResponse = IDL.Record({
  'taskCount' : IDL.Nat,
  'items' : IDL.Vec(DueDateTaskDetails),
});
export const RevenueResponse = IDL.Record({
  'totalCollected' : IDL.Nat,
  'totalOutstanding' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const RevenueCardType = IDL.Variant({
  'totalCollected' : IDL.Null,
  'totalOutstanding' : IDL.Null,
  'totalRevenue' : IDL.Null,
});
export const RevenueTaskDetails = IDL.Record({
  'paymentStatus' : Type,
  'clientName' : IDL.Text,
  'bill' : IDL.Opt(IDL.Text),
  'advanceReceived' : IDL.Opt(IDL.Nat),
  'taskName' : IDL.Text,
  'outstandingAmount' : IDL.Opt(IDL.Nat),
});
export const RevenueModalResponse = IDL.Record({
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(RevenueTaskDetails),
});
export const TaskId = IDL.Nat32;
export const PublicSearchFilter = IDL.Record({ 'searchTerm' : IDL.Text });
export const PublicClient = IDL.Record({
  'status' : Type__4,
  'name' : IDL.Text,
});
export const PublicTask = IDL.Record({
  'status' : Type__2,
  'title' : IDL.Text,
  'paymentStatus' : Type,
  'subType' : IDL.Opt(IDL.Text),
  'completionDate' : IDL.Opt(Time),
  'clientName' : IDL.Text,
  'dueDate' : IDL.Opt(Time),
  'taskType' : Type__3,
  'comment' : IDL.Opt(IDL.Text),
  'assignedDate' : IDL.Opt(Time),
  'assignedName' : IDL.Text,
  'taskSubType' : Type__3,
});
export const PublicTaskByAssignee = IDL.Record({
  'status' : Type__2,
  'title' : IDL.Text,
  'paymentStatus' : Type,
  'completionDate' : IDL.Opt(Time),
  'clientName' : IDL.Text,
  'dueDate' : IDL.Opt(Time),
  'taskStatus' : Type__2,
  'taskType' : Type__3,
  'comment' : IDL.Opt(IDL.Text),
  'assignedDate' : IDL.Opt(Time),
  'assignedName' : IDL.Text,
  'taskSubType' : Type__3,
});
export const PublicTeamMember = IDL.Record({ 'name' : IDL.Text });
export const ToDoItemUpdate = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClients' : IDL.Func([IDL.Vec(Client)], [], []),
  'addToDoItem' : IDL.Func([ToDoItemCreate], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTask' : IDL.Func([IDL.Nat32, IDL.Principal, IDL.Text], [], []),
  'bulkImportClients' : IDL.Func([IDL.Vec(Client)], [], []),
  'bulkImportTasks' : IDL.Func([IDL.Vec(Task)], [], []),
  'bulkImportTeamMembers' : IDL.Func([IDL.Vec(TeamMemberData)], [], []),
  'createTask' : IDL.Func([Task], [], []),
  'createTeamMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'deleteClient' : IDL.Func([IDL.Nat32], [], []),
  'deleteClients' : IDL.Func([IDL.Vec(IDL.Nat32)], [], []),
  'deleteTask' : IDL.Func([IDL.Nat32], [], []),
  'deleteTasks' : IDL.Func([IDL.Vec(IDL.Nat32)], [], []),
  'deleteToDoItem' : IDL.Func([ToDoAuthRequest], [], []),
  'filterAndSortByClientName' : IDL.Func(
      [TaskFilter, IDL.Bool],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'filterTasks' : IDL.Func([TaskFilter], [IDL.Vec(Task)], ['query']),
  'filterTasksByDate' : IDL.Func(
      [Time, IDL.Bool, IDL.Bool],
      [DateSearchResult],
      ['query'],
    ),
  'filterToDosByUser' : IDL.Func(
      [IDL.Principal, ToDoFilterType],
      [IDL.Vec(ToDoItem)],
      ['query'],
    ),
  'getAllTasksForExport' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getDashboardTasks' : IDL.Func(
      [DashboardTasksRequest],
      [DashboardTasksResponse],
      ['query'],
    ),
  'getDueDateCardCounts' : IDL.Func([], [DueDateCountResponse], ['query']),
  'getDueDateModalData' : IDL.Func(
      [IDL.Opt(DueDateDayType), IDL.Opt(Time)],
      [IDL.Opt(DueDateModalResponse)],
      ['query'],
    ),
  'getRevenueCardsData' : IDL.Func([], [RevenueResponse], ['query']),
  'getRevenueModalData' : IDL.Func(
      [RevenueCardType],
      [RevenueModalResponse],
      ['query'],
    ),
  'getSelectedTasksForExport' : IDL.Func(
      [IDL.Vec(TaskId)],
      [IDL.Vec(Task)],
      ['query'],
    ),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByStatus' : IDL.Func([Type__2], [IDL.Vec(Task)], ['query']),
  'getTasksByType' : IDL.Func([Type__3], [IDL.Vec(Task)], ['query']),
  'getTasksForExport' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getToDosForExport' : IDL.Func([], [IDL.Vec(ToDoItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserToDos' : IDL.Func([IDL.Principal], [IDL.Vec(ToDoItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publicSearchClients' : IDL.Func(
      [PublicSearchFilter],
      [IDL.Vec(PublicClient)],
      ['query'],
    ),
  'publicSearchTasks' : IDL.Func(
      [PublicSearchFilter],
      [IDL.Vec(PublicTask)],
      ['query'],
    ),
  'publicSearchTasksByAssignee' : IDL.Func(
      [PublicSearchFilter],
      [IDL.Vec(PublicTaskByAssignee)],
      ['query'],
    ),
  'publicSearchTeamMembers' : IDL.Func(
      [PublicSearchFilter],
      [IDL.Vec(PublicTeamMember)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchClients' : IDL.Func([IDL.Text], [IDL.Vec(Client)], ['query']),
  'searchTasksByDate' : IDL.Func([Time], [DateSearchResult], ['query']),
  'updateClient' : IDL.Func([IDL.Nat32, Client], [], []),
  'updateClients' : IDL.Func([IDL.Vec(IDL.Nat32), IDL.Vec(Client)], [], []),
  'updatePaymentStatus' : IDL.Func(
      [IDL.Nat32, Type, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateTask' : IDL.Func([IDL.Nat32, Task], [], []),
  'updateTaskBill' : IDL.Func(
      [IDL.Nat32, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateTaskCaptains' : IDL.Func([IDL.Nat32, IDL.Vec(IDL.Principal)], [], []),
  'updateTaskComment' : IDL.Func([IDL.Nat32, IDL.Opt(IDL.Text)], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat32, Type__2], [], []),
  'updateTasks' : IDL.Func([IDL.Vec(IDL.Nat32), IDL.Vec(Task)], [], []),
  'updateToDoItem' : IDL.Func([ToDoAuthRequest, ToDoItemUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Type__4 = IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null });
  const Type__1 = IDL.Variant({
    'none' : IDL.Null,
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
  });
  const Type__3 = IDL.Variant({
    'GST' : IDL.Null,
    'TDS' : IDL.Null,
    'ITNotice' : IDL.Null,
    'Accounts' : IDL.Null,
    'Audit' : IDL.Null,
    'Other' : IDL.Null,
    'FormFiling' : IDL.Null,
    'CACertificate' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat32,
    'pan' : IDL.Opt(IDL.Text),
    'status' : Type__4,
    'subCategory' : IDL.Opt(IDL.Text),
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'recurring' : Type__1,
    'gstin' : IDL.Opt(IDL.Text),
    'taskCategory' : Type__3,
  });
  const Time = IDL.Int;
  const ToDoItemCreate = IDL.Record({
    'title' : IDL.Text,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Type__2 = IDL.Variant({
    'pending' : IDL.Null,
    'hold' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'docsPending' : IDL.Null,
  });
  const Type = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat32,
    'status' : Type__2,
    'title' : IDL.Text,
    'clientId' : IDL.Nat32,
    'paymentStatus' : Type,
    'subType' : IDL.Opt(IDL.Text),
    'completionDate' : IDL.Opt(Time),
    'assignedTo' : IDL.Principal,
    'clientName' : IDL.Text,
    'assignmentDate' : IDL.Opt(Time),
    'bill' : IDL.Opt(IDL.Text),
    'advanceReceived' : IDL.Opt(IDL.Nat),
    'createdAt' : Time,
    'recurring' : Type__1,
    'dueDate' : IDL.Opt(Time),
    'manualAssignmentDate' : IDL.Opt(Time),
    'taskType' : Type__3,
    'comment' : IDL.Opt(IDL.Text),
    'outstandingAmount' : IDL.Opt(IDL.Nat),
    'captains' : IDL.Vec(IDL.Principal),
    'assignedName' : IDL.Text,
  });
  const TeamMemberData = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const ToDoAuthRequest = IDL.Record({
    'owner' : IDL.Principal,
    'todoId' : IDL.Nat32,
  });
  const TaskFilter = IDL.Record({
    'status' : IDL.Opt(Type__2),
    'paymentStatus' : IDL.Opt(Type),
    'subType' : IDL.Opt(IDL.Text),
    'assigneeName' : IDL.Opt(IDL.Text),
    'searchTerm' : IDL.Opt(IDL.Text),
    'taskType' : IDL.Opt(Type__3),
    'comment' : IDL.Opt(IDL.Text),
  });
  const DateSearchResult = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'date' : Time,
  });
  const ToDoFilterType = IDL.Variant({ 'all' : IDL.Null, 'today' : IDL.Null });
  const ToDoItemOwner = IDL.Principal;
  const ToDoItem = IDL.Record({
    'id' : IDL.Nat32,
    'title' : IDL.Text,
    'owner' : ToDoItemOwner,
    'modifiedAt' : Time,
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Opt(IDL.Text),
  });
  const TeamMember = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const SortDirection = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const DashboardTasksRequest = IDL.Record({
    'completionDateSortDirection' : SortDirection,
    'dueDateSortDirection' : SortDirection,
  });
  const DashboardTasksResponse = IDL.Record({
    'completionDateSorted' : IDL.Vec(Task),
    'dueDateSorted' : IDL.Vec(Task),
  });
  const DueDateCountResponse = IDL.Record({
    'dueTodayCount' : IDL.Nat,
    'dueTomorrowCount' : IDL.Nat,
    'customDateCount' : IDL.Nat,
    'anyDateCount' : IDL.Nat,
  });
  const DueDateDayType = IDL.Variant({
    'dueTomorrow' : IDL.Null,
    'dueToday' : IDL.Null,
    'anyDate' : IDL.Null,
    'customDate' : Time,
  });
  const DueDateTaskDetails = IDL.Record({
    'status' : Type__2,
    'assignee' : IDL.Text,
    'paymentStatus' : Type,
    'clientName' : IDL.Text,
    'dueDate' : IDL.Opt(Time),
    'taskTitle' : IDL.Text,
    'comments' : IDL.Opt(IDL.Text),
  });
  const DueDateModalResponse = IDL.Record({
    'taskCount' : IDL.Nat,
    'items' : IDL.Vec(DueDateTaskDetails),
  });
  const RevenueResponse = IDL.Record({
    'totalCollected' : IDL.Nat,
    'totalOutstanding' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const RevenueCardType = IDL.Variant({
    'totalCollected' : IDL.Null,
    'totalOutstanding' : IDL.Null,
    'totalRevenue' : IDL.Null,
  });
  const RevenueTaskDetails = IDL.Record({
    'paymentStatus' : Type,
    'clientName' : IDL.Text,
    'bill' : IDL.Opt(IDL.Text),
    'advanceReceived' : IDL.Opt(IDL.Nat),
    'taskName' : IDL.Text,
    'outstandingAmount' : IDL.Opt(IDL.Nat),
  });
  const RevenueModalResponse = IDL.Record({
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(RevenueTaskDetails),
  });
  const TaskId = IDL.Nat32;
  const PublicSearchFilter = IDL.Record({ 'searchTerm' : IDL.Text });
  const PublicClient = IDL.Record({ 'status' : Type__4, 'name' : IDL.Text });
  const PublicTask = IDL.Record({
    'status' : Type__2,
    'title' : IDL.Text,
    'paymentStatus' : Type,
    'subType' : IDL.Opt(IDL.Text),
    'completionDate' : IDL.Opt(Time),
    'clientName' : IDL.Text,
    'dueDate' : IDL.Opt(Time),
    'taskType' : Type__3,
    'comment' : IDL.Opt(IDL.Text),
    'assignedDate' : IDL.Opt(Time),
    'assignedName' : IDL.Text,
    'taskSubType' : Type__3,
  });
  const PublicTaskByAssignee = IDL.Record({
    'status' : Type__2,
    'title' : IDL.Text,
    'paymentStatus' : Type,
    'completionDate' : IDL.Opt(Time),
    'clientName' : IDL.Text,
    'dueDate' : IDL.Opt(Time),
    'taskStatus' : Type__2,
    'taskType' : Type__3,
    'comment' : IDL.Opt(IDL.Text),
    'assignedDate' : IDL.Opt(Time),
    'assignedName' : IDL.Text,
    'taskSubType' : Type__3,
  });
  const PublicTeamMember = IDL.Record({ 'name' : IDL.Text });
  const ToDoItemUpdate = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClients' : IDL.Func([IDL.Vec(Client)], [], []),
    'addToDoItem' : IDL.Func([ToDoItemCreate], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTask' : IDL.Func([IDL.Nat32, IDL.Principal, IDL.Text], [], []),
    'bulkImportClients' : IDL.Func([IDL.Vec(Client)], [], []),
    'bulkImportTasks' : IDL.Func([IDL.Vec(Task)], [], []),
    'bulkImportTeamMembers' : IDL.Func([IDL.Vec(TeamMemberData)], [], []),
    'createTask' : IDL.Func([Task], [], []),
    'createTeamMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'deleteClient' : IDL.Func([IDL.Nat32], [], []),
    'deleteClients' : IDL.Func([IDL.Vec(IDL.Nat32)], [], []),
    'deleteTask' : IDL.Func([IDL.Nat32], [], []),
    'deleteTasks' : IDL.Func([IDL.Vec(IDL.Nat32)], [], []),
    'deleteToDoItem' : IDL.Func([ToDoAuthRequest], [], []),
    'filterAndSortByClientName' : IDL.Func(
        [TaskFilter, IDL.Bool],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'filterTasks' : IDL.Func([TaskFilter], [IDL.Vec(Task)], ['query']),
    'filterTasksByDate' : IDL.Func(
        [Time, IDL.Bool, IDL.Bool],
        [DateSearchResult],
        ['query'],
      ),
    'filterToDosByUser' : IDL.Func(
        [IDL.Principal, ToDoFilterType],
        [IDL.Vec(ToDoItem)],
        ['query'],
      ),
    'getAllTasksForExport' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getDashboardTasks' : IDL.Func(
        [DashboardTasksRequest],
        [DashboardTasksResponse],
        ['query'],
      ),
    'getDueDateCardCounts' : IDL.Func([], [DueDateCountResponse], ['query']),
    'getDueDateModalData' : IDL.Func(
        [IDL.Opt(DueDateDayType), IDL.Opt(Time)],
        [IDL.Opt(DueDateModalResponse)],
        ['query'],
      ),
    'getRevenueCardsData' : IDL.Func([], [RevenueResponse], ['query']),
    'getRevenueModalData' : IDL.Func(
        [RevenueCardType],
        [RevenueModalResponse],
        ['query'],
      ),
    'getSelectedTasksForExport' : IDL.Func(
        [IDL.Vec(TaskId)],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByStatus' : IDL.Func([Type__2], [IDL.Vec(Task)], ['query']),
    'getTasksByType' : IDL.Func([Type__3], [IDL.Vec(Task)], ['query']),
    'getTasksForExport' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getToDosForExport' : IDL.Func([], [IDL.Vec(ToDoItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserToDos' : IDL.Func([IDL.Principal], [IDL.Vec(ToDoItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publicSearchClients' : IDL.Func(
        [PublicSearchFilter],
        [IDL.Vec(PublicClient)],
        ['query'],
      ),
    'publicSearchTasks' : IDL.Func(
        [PublicSearchFilter],
        [IDL.Vec(PublicTask)],
        ['query'],
      ),
    'publicSearchTasksByAssignee' : IDL.Func(
        [PublicSearchFilter],
        [IDL.Vec(PublicTaskByAssignee)],
        ['query'],
      ),
    'publicSearchTeamMembers' : IDL.Func(
        [PublicSearchFilter],
        [IDL.Vec(PublicTeamMember)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchClients' : IDL.Func([IDL.Text], [IDL.Vec(Client)], ['query']),
    'searchTasksByDate' : IDL.Func([Time], [DateSearchResult], ['query']),
    'updateClient' : IDL.Func([IDL.Nat32, Client], [], []),
    'updateClients' : IDL.Func([IDL.Vec(IDL.Nat32), IDL.Vec(Client)], [], []),
    'updatePaymentStatus' : IDL.Func(
        [IDL.Nat32, Type, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateTask' : IDL.Func([IDL.Nat32, Task], [], []),
    'updateTaskBill' : IDL.Func(
        [IDL.Nat32, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateTaskCaptains' : IDL.Func(
        [IDL.Nat32, IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
    'updateTaskComment' : IDL.Func([IDL.Nat32, IDL.Opt(IDL.Text)], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat32, Type__2], [], []),
    'updateTasks' : IDL.Func([IDL.Vec(IDL.Nat32), IDL.Vec(Task)], [], []),
    'updateToDoItem' : IDL.Func([ToDoAuthRequest, ToDoItemUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };