/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : number,
  'pan' : [] | [string],
  'status' : Type__4,
  'subCategory' : [] | [string],
  'contactInfo' : string,
  'name' : string,
  'recurring' : Type__1,
  'gstin' : [] | [string],
  'taskCategory' : Type__3,
}
export interface DashboardTasksRequest {
  'completionDateSortDirection' : SortDirection,
  'dueDateSortDirection' : SortDirection,
}
export interface DashboardTasksResponse {
  'completionDateSorted' : Array<Task>,
  'dueDateSorted' : Array<Task>,
}
export interface DateSearchResult { 'tasks' : Array<Task>, 'date' : Time }
export interface DueDateCountResponse {
  'dueTodayCount' : bigint,
  'dueTomorrowCount' : bigint,
  'customDateCount' : bigint,
  'anyDateCount' : bigint,
}
export type DueDateDayType = { 'dueTomorrow' : null } |
  { 'dueToday' : null } |
  { 'anyDate' : null } |
  { 'customDate' : Time };
export interface DueDateModalResponse {
  'taskCount' : bigint,
  'items' : Array<DueDateTaskDetails>,
}
export interface DueDateTaskDetails {
  'status' : Type__2,
  'assignee' : string,
  'paymentStatus' : Type,
  'clientName' : string,
  'dueDate' : [] | [Time],
  'taskTitle' : string,
  'comments' : [] | [string],
}
export interface PublicClient { 'status' : Type__4, 'name' : string }
export interface PublicSearchFilter { 'searchTerm' : string }
export interface PublicTask {
  'status' : Type__2,
  'title' : string,
  'paymentStatus' : Type,
  'subType' : [] | [string],
  'completionDate' : [] | [Time],
  'clientName' : string,
  'dueDate' : [] | [Time],
  'taskType' : Type__3,
  'comment' : [] | [string],
  'assignedDate' : [] | [Time],
  'assignedName' : string,
  'taskSubType' : Type__3,
}
export interface PublicTaskByAssignee {
  'status' : Type__2,
  'title' : string,
  'paymentStatus' : Type,
  'completionDate' : [] | [Time],
  'clientName' : string,
  'dueDate' : [] | [Time],
  'taskStatus' : Type__2,
  'taskType' : Type__3,
  'comment' : [] | [string],
  'assignedDate' : [] | [Time],
  'assignedName' : string,
  'taskSubType' : Type__3,
}
export interface PublicTeamMember { 'name' : string }
export type RevenueCardType = { 'totalCollected' : null } |
  { 'totalOutstanding' : null } |
  { 'totalRevenue' : null };
export interface RevenueModalResponse {
  'totalAmount' : bigint,
  'items' : Array<RevenueTaskDetails>,
}
export interface RevenueResponse {
  'totalCollected' : bigint,
  'totalOutstanding' : bigint,
  'totalRevenue' : bigint,
}
export interface RevenueTaskDetails {
  'paymentStatus' : Type,
  'clientName' : string,
  'bill' : [] | [string],
  'advanceReceived' : [] | [bigint],
  'taskName' : string,
  'outstandingAmount' : [] | [bigint],
}
export type SortDirection = { 'asc' : null } |
  { 'desc' : null };
export interface Task {
  'id' : number,
  'status' : Type__2,
  'title' : string,
  'clientId' : number,
  'paymentStatus' : Type,
  'subType' : [] | [string],
  'completionDate' : [] | [Time],
  'assignedTo' : Principal,
  'clientName' : string,
  'assignmentDate' : [] | [Time],
  'bill' : [] | [string],
  'advanceReceived' : [] | [bigint],
  'createdAt' : Time,
  'recurring' : Type__1,
  'dueDate' : [] | [Time],
  'manualAssignmentDate' : [] | [Time],
  'taskType' : Type__3,
  'comment' : [] | [string],
  'outstandingAmount' : [] | [bigint],
  'assignedName' : string,
}
export interface TaskFilter {
  'status' : [] | [Type__2],
  'paymentStatus' : [] | [Type],
  'subType' : [] | [string],
  'assigneeName' : [] | [string],
  'searchTerm' : [] | [string],
  'taskType' : [] | [Type__3],
  'comment' : [] | [string],
}
export type TaskId = number;
export interface TeamMember { 'principal' : Principal, 'name' : string }
export interface TeamMemberData { 'principal' : Principal, 'name' : string }
export type Time = bigint;
export interface ToDoAuthRequest { 'owner' : Principal, 'todoId' : number }
export type ToDoFilterType = { 'all' : null } |
  { 'today' : null };
export interface ToDoItem {
  'id' : number,
  'title' : string,
  'owner' : ToDoItemOwner,
  'modifiedAt' : Time,
  'createdAt' : Time,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : [] | [string],
}
export interface ToDoItemCreate {
  'title' : string,
  'dueDate' : [] | [Time],
  'description' : [] | [string],
}
export type ToDoItemOwner = Principal;
export interface ToDoItemUpdate {
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : [] | [string],
}
export type Type = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export type Type__1 = { 'none' : null } |
  { 'quarterly' : null } |
  { 'monthly' : null } |
  { 'yearly' : null };
export type Type__2 = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Type__3 = { 'GST' : null } |
  { 'TDS' : null } |
  { 'ITNotice' : null } |
  { 'Accounts' : null } |
  { 'Audit' : null } |
  { 'Other' : null } |
  { 'FormFiling' : null } |
  { 'CACertificate' : null };
export type Type__4 = { 'active' : null } |
  { 'inactive' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClients' : ActorMethod<[Array<Client>], undefined>,
  'addToDoItem' : ActorMethod<[ToDoItemCreate], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTask' : ActorMethod<[number, Principal, string], undefined>,
  'bulkImportClients' : ActorMethod<[Array<Client>], undefined>,
  'bulkImportTasks' : ActorMethod<[Array<Task>], undefined>,
  'bulkImportTeamMembers' : ActorMethod<[Array<TeamMemberData>], undefined>,
  'createTask' : ActorMethod<[Task], undefined>,
  'createTeamMember' : ActorMethod<[string, Principal], undefined>,
  'deleteClient' : ActorMethod<[number], undefined>,
  'deleteClients' : ActorMethod<[Uint32Array], undefined>,
  'deleteTask' : ActorMethod<[number], undefined>,
  'deleteTasks' : ActorMethod<[Uint32Array], undefined>,
  'deleteToDoItem' : ActorMethod<[ToDoAuthRequest], undefined>,
  'filterAndSortByClientName' : ActorMethod<[TaskFilter, boolean], Array<Task>>,
  'filterTasks' : ActorMethod<[TaskFilter], Array<Task>>,
  'filterTasksByDate' : ActorMethod<[Time, boolean, boolean], DateSearchResult>,
  'filterToDosByUser' : ActorMethod<
    [Principal, ToDoFilterType],
    Array<ToDoItem>
  >,
  'getAllTasksForExport' : ActorMethod<[], Array<Task>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getDashboardTasks' : ActorMethod<
    [DashboardTasksRequest],
    DashboardTasksResponse
  >,
  'getDueDateCardCounts' : ActorMethod<[], DueDateCountResponse>,
  'getDueDateModalData' : ActorMethod<
    [[] | [DueDateDayType], [] | [Time]],
    [] | [DueDateModalResponse]
  >,
  'getRevenueCardsData' : ActorMethod<[], RevenueResponse>,
  'getRevenueModalData' : ActorMethod<[RevenueCardType], RevenueModalResponse>,
  'getSelectedTasksForExport' : ActorMethod<[Uint32Array], Array<Task>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTasksByStatus' : ActorMethod<[Type__2], Array<Task>>,
  'getTasksByType' : ActorMethod<[Type__3], Array<Task>>,
  'getTasksForExport' : ActorMethod<[], Array<Task>>,
  'getToDosForExport' : ActorMethod<[], Array<ToDoItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserToDos' : ActorMethod<[Principal], Array<ToDoItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publicSearchClients' : ActorMethod<
    [PublicSearchFilter],
    Array<PublicClient>
  >,
  'publicSearchTasks' : ActorMethod<[PublicSearchFilter], Array<PublicTask>>,
  'publicSearchTasksByAssignee' : ActorMethod<
    [PublicSearchFilter],
    Array<PublicTaskByAssignee>
  >,
  'publicSearchTeamMembers' : ActorMethod<
    [PublicSearchFilter],
    Array<PublicTeamMember>
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchClients' : ActorMethod<[string], Array<Client>>,
  'searchTasksByDate' : ActorMethod<[Time], DateSearchResult>,
  'updateClient' : ActorMethod<[number, Client], undefined>,
  'updateClients' : ActorMethod<[Uint32Array, Array<Client>], undefined>,
  'updatePaymentStatus' : ActorMethod<
    [number, Type, [] | [bigint], [] | [string]],
    undefined
  >,
  'updateTask' : ActorMethod<[number, Task], undefined>,
  'updateTaskBill' : ActorMethod<
    [number, [] | [string], [] | [bigint]],
    undefined
  >,
  'updateTaskComment' : ActorMethod<[number, [] | [string]], undefined>,
  'updateTaskStatus' : ActorMethod<[number, Type__2], undefined>,
  'updateTasks' : ActorMethod<[Uint32Array, Array<Task>], undefined>,
  'updateToDoItem' : ActorMethod<[ToDoAuthRequest, ToDoItemUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];