/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PublicTaskByAssignee {
    status: Type__2;
    title: string;
    paymentStatus: Type;
    completionDate?: Time;
    clientName: string;
    dueDate?: Time;
    taskStatus: Type__2;
    taskType: Type__3;
    comment?: string;
    assignedDate?: Time;
    assignedName: string;
    taskSubType: Type__3;
}
export type Time = bigint;
export interface DueDateModalResponse {
    taskCount: bigint;
    items: Array<DueDateTaskDetails>;
}
export type DueDateDayType = {
    __kind__: "dueTomorrow";
    dueTomorrow: null;
} | {
    __kind__: "dueToday";
    dueToday: null;
} | {
    __kind__: "anyDate";
    anyDate: null;
} | {
    __kind__: "customDate";
    customDate: Time;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DueDateCountResponse {
    dueTodayCount: bigint;
    dueTomorrowCount: bigint;
    customDateCount: bigint;
    anyDateCount: bigint;
}
export interface Task {
    id: number;
    status: Type__2;
    title: string;
    clientId: number;
    paymentStatus: Type;
    subType?: string;
    completionDate?: Time;
    assignedTo: Principal;
    clientName: string;
    assignmentDate?: Time;
    bill?: string;
    advanceReceived?: bigint;
    createdAt: Time;
    recurring: Type__1;
    dueDate?: Time;
    manualAssignmentDate?: Time;
    taskType: Type__3;
    comment?: string;
    outstandingAmount?: bigint;
    captains: Array<Principal>;
    assignedName: string;
}
export interface RevenueTaskDetails {
    paymentStatus: Type;
    clientName: string;
    bill?: string;
    advanceReceived?: bigint;
    taskName: string;
    outstandingAmount?: bigint;
}
export interface DashboardTasksResponse {
    completionDateSorted: Array<Task>;
    dueDateSorted: Array<Task>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ToDoItemUpdate {
    title: string;
    completed: boolean;
    dueDate?: Time;
    description?: string;
}
export interface PublicClient {
    status: Type__4;
    name: string;
}
export interface DashboardTasksRequest {
    completionDateSortDirection: SortDirection;
    dueDateSortDirection: SortDirection;
}
export interface PublicSearchFilter {
    searchTerm: string;
}
export interface DateSearchResult {
    tasks: Array<Task>;
    date: Time;
}
export interface Client {
    id: number;
    pan?: string;
    status: Type__4;
    subCategory?: string;
    contactInfo: string;
    name: string;
    recurring: Type__1;
    gstin?: string;
    taskCategory: Type__3;
}
export interface ToDoItemCreate {
    title: string;
    dueDate?: Time;
    description?: string;
}
export interface RevenueResponse {
    totalCollected: bigint;
    totalOutstanding: bigint;
    totalRevenue: bigint;
}
export interface ToDoItem {
    id: number;
    title: string;
    owner: ToDoItemOwner;
    modifiedAt: Time;
    createdAt: Time;
    completed: boolean;
    dueDate?: Time;
    description?: string;
}
export interface PublicTask {
    status: Type__2;
    title: string;
    paymentStatus: Type;
    subType?: string;
    completionDate?: Time;
    clientName: string;
    dueDate?: Time;
    taskType: Type__3;
    comment?: string;
    assignedDate?: Time;
    assignedName: string;
    taskSubType: Type__3;
}
export interface TeamMemberData {
    principal: Principal;
    name: string;
}
export interface PublicTeamMember {
    name: string;
}
export type TaskId = number;
export interface RevenueModalResponse {
    totalAmount: bigint;
    items: Array<RevenueTaskDetails>;
}
export interface TeamMember {
    principal: Principal;
    name: string;
}
export type ToDoItemOwner = Principal;
export interface TaskFilter {
    status?: Type__2;
    paymentStatus?: Type;
    subType?: string;
    assigneeName?: string;
    searchTerm?: string;
    taskType?: Type__3;
    comment?: string;
}
export interface DueDateTaskDetails {
    status: Type__2;
    assignee: string;
    paymentStatus: Type;
    clientName: string;
    dueDate?: Time;
    taskTitle: string;
    comments?: string;
}
export interface ToDoAuthRequest {
    owner: Principal;
    todoId: number;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum RevenueCardType {
    totalCollected = "totalCollected",
    totalOutstanding = "totalOutstanding",
    totalRevenue = "totalRevenue"
}
export enum SortDirection {
    asc = "asc",
    desc = "desc"
}
export enum ToDoFilterType {
    all = "all",
    today = "today"
}
export enum Type {
    pending = "pending",
    paid = "paid",
    overdue = "overdue"
}
export enum Type__1 {
    none = "none",
    quarterly = "quarterly",
    monthly = "monthly",
    yearly = "yearly"
}
export enum Type__2 {
    pending = "pending",
    hold = "hold",
    completed = "completed",
    inProgress = "inProgress",
    docsPending = "docsPending"
}
export enum Type__3 {
    GST = "GST",
    TDS = "TDS",
    ITNotice = "ITNotice",
    Accounts = "Accounts",
    Audit = "Audit",
    Other = "Other",
    FormFiling = "FormFiling",
    CACertificate = "CACertificate"
}
export enum Type__4 {
    active = "active",
    inactive = "inactive"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addClients(newClients: Array<Client>): Promise<void>;
    addToDoItem(toDoItem: ToDoItemCreate): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignTask(taskId: number, assignedTo: Principal, assignedName: string): Promise<void>;
    bulkImportClients(clientsToImport: Array<Client>): Promise<void>;
    bulkImportTasks(tasksToImport: Array<Task>): Promise<void>;
    bulkImportTeamMembers(teamMembersToImport: Array<TeamMemberData>): Promise<void>;
    createTask(newTask: Task): Promise<void>;
    createTeamMember(name: string, principal: Principal): Promise<void>;
    deleteClient(clientId: number): Promise<void>;
    deleteClients(clientIds: Uint32Array): Promise<void>;
    deleteTask(taskId: number): Promise<void>;
    deleteTasks(taskIds: Uint32Array): Promise<void>;
    deleteToDoItem(request: ToDoAuthRequest): Promise<void>;
    filterAndSortByClientName(filter: TaskFilter, ascending: boolean): Promise<Array<Task>>;
    filterTasks(params: TaskFilter): Promise<Array<Task>>;
    filterTasksByDate(targetDate: Time, _includeDueDate: boolean, _includeCompletionDate: boolean): Promise<DateSearchResult>;
    filterToDosByUser(user: Principal, filterType: ToDoFilterType): Promise<Array<ToDoItem>>;
    getAllTasksForExport(): Promise<Array<Task>>;
    getAllTeamMembers(): Promise<Array<TeamMember>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClients(): Promise<Array<Client>>;
    getDashboardTasks(request: DashboardTasksRequest): Promise<DashboardTasksResponse>;
    getDueDateCardCounts(): Promise<DueDateCountResponse>;
    getDueDateModalData(dayType: DueDateDayType | null, customDate: Time | null): Promise<DueDateModalResponse | null>;
    getRevenueCardsData(): Promise<RevenueResponse>;
    getRevenueModalData(cardType: RevenueCardType): Promise<RevenueModalResponse>;
    getSelectedTasksForExport(selectedTaskIds: Uint32Array): Promise<Array<Task>>;
    getTasks(): Promise<Array<Task>>;
    getTasksByStatus(status: Type__2): Promise<Array<Task>>;
    getTasksByType(taskType: Type__3): Promise<Array<Task>>;
    getTasksForExport(): Promise<Array<Task>>;
    getToDosForExport(): Promise<Array<ToDoItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserToDos(user: Principal): Promise<Array<ToDoItem>>;
    isCallerAdmin(): Promise<boolean>;
    publicSearchClients(filter: PublicSearchFilter): Promise<Array<PublicClient>>;
    publicSearchTasks(filter: PublicSearchFilter): Promise<Array<PublicTask>>;
    publicSearchTasksByAssignee(filter: PublicSearchFilter): Promise<Array<PublicTaskByAssignee>>;
    publicSearchTeamMembers(filter: PublicSearchFilter): Promise<Array<PublicTeamMember>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchClients(searchTerm: string): Promise<Array<Client>>;
    searchTasksByDate(date: Time): Promise<DateSearchResult>;
    updateClient(clientId: number, updatedClient: Client): Promise<void>;
    updateClients(clientIds: Uint32Array, updatedClients: Array<Client>): Promise<void>;
    updatePaymentStatus(taskId: number, paymentStatus: Type, advanceReceived: bigint | null, bill: string | null): Promise<void>;
    updateTask(taskId: number, updatedTask: Task): Promise<void>;
    updateTaskBill(taskId: number, bill: string | null, advanceReceived: bigint | null): Promise<void>;
    updateTaskCaptains(taskId: number, captains: Array<Principal>): Promise<void>;
    updateTaskComment(taskId: number, comment: string | null): Promise<void>;
    updateTaskStatus(taskId: number, status: Type__2): Promise<void>;
    updateTasks(taskIds: Uint32Array, updatedTasks: Array<Task>): Promise<void>;
    updateToDoItem(request: ToDoAuthRequest, updatedToDoItem: ToDoItemUpdate): Promise<void>;
}
import type { Client as _Client, DashboardTasksRequest as _DashboardTasksRequest, DashboardTasksResponse as _DashboardTasksResponse, DateSearchResult as _DateSearchResult, DueDateDayType as _DueDateDayType, DueDateModalResponse as _DueDateModalResponse, DueDateTaskDetails as _DueDateTaskDetails, PublicClient as _PublicClient, PublicTask as _PublicTask, PublicTaskByAssignee as _PublicTaskByAssignee, RevenueCardType as _RevenueCardType, RevenueModalResponse as _RevenueModalResponse, RevenueTaskDetails as _RevenueTaskDetails, SortDirection as _SortDirection, Task as _Task, TaskFilter as _TaskFilter, Time as _Time, ToDoFilterType as _ToDoFilterType, ToDoItem as _ToDoItem, ToDoItemCreate as _ToDoItemCreate, ToDoItemOwner as _ToDoItemOwner, ToDoItemUpdate as _ToDoItemUpdate, Type as _Type, Type__1 as _Type__1, Type__2 as _Type__2, Type__3 as _Type__3, Type__4 as _Type__4, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addClients(arg0: Array<Client>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClients(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClients(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addToDoItem(arg0: ToDoItemCreate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToDoItem(to_candid_ToDoItemCreate_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToDoItem(to_candid_ToDoItemCreate_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTask(arg0: number, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTask(arg0, arg1, arg2);
            return result;
        }
    }
    async bulkImportClients(arg0: Array<Client>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportClients(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportClients(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkImportTasks(arg0: Array<Task>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportTasks(to_candid_vec_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportTasks(to_candid_vec_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkImportTeamMembers(arg0: Array<TeamMemberData>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportTeamMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportTeamMembers(arg0);
            return result;
        }
    }
    async createTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_Task_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_Task_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTeamMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeamMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeamMember(arg0, arg1);
            return result;
        }
    }
    async deleteClient(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteClients(arg0: Uint32Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClients(arg0);
            return result;
        }
    }
    async deleteTask(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteTasks(arg0: Uint32Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTasks(arg0);
            return result;
        }
    }
    async deleteToDoItem(arg0: ToDoAuthRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteToDoItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteToDoItem(arg0);
            return result;
        }
    }
    async filterAndSortByClientName(arg0: TaskFilter, arg1: boolean): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterAndSortByClientName(to_candid_TaskFilter_n28(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterAndSortByClientName(to_candid_TaskFilter_n28(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterTasks(arg0: TaskFilter): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterTasks(to_candid_TaskFilter_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterTasks(to_candid_TaskFilter_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterTasksByDate(arg0: Time, arg1: boolean, arg2: boolean): Promise<DateSearchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.filterTasksByDate(arg0, arg1, arg2);
                return from_candid_DateSearchResult_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterTasksByDate(arg0, arg1, arg2);
            return from_candid_DateSearchResult_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterToDosByUser(arg0: Principal, arg1: ToDoFilterType): Promise<Array<ToDoItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterToDosByUser(arg0, to_candid_ToDoFilterType_n45(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterToDosByUser(arg0, to_candid_ToDoFilterType_n45(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasksForExport(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasksForExport();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasksForExport();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeamMembers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClients();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClients();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardTasks(arg0: DashboardTasksRequest): Promise<DashboardTasksResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardTasks(to_candid_DashboardTasksRequest_n58(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DashboardTasksResponse_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardTasks(to_candid_DashboardTasksRequest_n58(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DashboardTasksResponse_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDueDateCardCounts(): Promise<DueDateCountResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueDateCardCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueDateCardCounts();
            return result;
        }
    }
    async getDueDateModalData(arg0: DueDateDayType | null, arg1: Time | null): Promise<DueDateModalResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueDateModalData(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueDateModalData(to_candid_opt_n64(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n67(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueCardsData(): Promise<RevenueResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueCardsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueCardsData();
            return result;
        }
    }
    async getRevenueModalData(arg0: RevenueCardType): Promise<RevenueModalResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueModalData(to_candid_RevenueCardType_n74(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RevenueModalResponse_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueModalData(to_candid_RevenueCardType_n74(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RevenueModalResponse_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSelectedTasksForExport(arg0: Uint32Array): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSelectedTasksForExport(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSelectedTasksForExport(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByStatus(arg0: Type__2): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByStatus(to_candid_Type__2_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByStatus(to_candid_Type__2_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByType(arg0: Type__3): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByType(to_candid_Type__3_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByType(to_candid_Type__3_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForExport(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForExport();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForExport();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToDosForExport(): Promise<Array<ToDoItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToDosForExport();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToDosForExport();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserToDos(arg0: Principal): Promise<Array<ToDoItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserToDos(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserToDos(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publicSearchClients(arg0: PublicSearchFilter): Promise<Array<PublicClient>> {
        if (this.processError) {
            try {
                const result = await this.actor.publicSearchClients(arg0);
                return from_candid_vec_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicSearchClients(arg0);
            return from_candid_vec_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async publicSearchTasks(arg0: PublicSearchFilter): Promise<Array<PublicTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.publicSearchTasks(arg0);
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicSearchTasks(arg0);
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async publicSearchTasksByAssignee(arg0: PublicSearchFilter): Promise<Array<PublicTaskByAssignee>> {
        if (this.processError) {
            try {
                const result = await this.actor.publicSearchTasksByAssignee(arg0);
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicSearchTasksByAssignee(arg0);
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async publicSearchTeamMembers(arg0: PublicSearchFilter): Promise<Array<PublicTeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.publicSearchTeamMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publicSearchTeamMembers(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchClients(arg0: string): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchClients(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchClients(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchTasksByDate(arg0: Time): Promise<DateSearchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTasksByDate(arg0);
                return from_candid_DateSearchResult_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTasksByDate(arg0);
            return from_candid_DateSearchResult_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClient(arg0: number, arg1: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, to_candid_Client_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, to_candid_Client_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateClients(arg0: Uint32Array, arg1: Array<Client>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClients(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClients(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: number, arg1: Type, arg2: bigint | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_Type_n26(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n90(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n91(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_Type_n26(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n90(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n91(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateTask(arg0: number, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_Task_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_Task_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskBill(arg0: number, arg1: string | null, arg2: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskBill(arg0, to_candid_opt_n91(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n90(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskBill(arg0, to_candid_opt_n91(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n90(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTaskCaptains(arg0: number, arg1: Array<Principal>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskCaptains(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskCaptains(arg0, arg1);
            return result;
        }
    }
    async updateTaskComment(arg0: number, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskComment(arg0, to_candid_opt_n91(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskComment(arg0, to_candid_opt_n91(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskStatus(arg0: number, arg1: Type__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_Type__2_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_Type__2_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTasks(arg0: Uint32Array, arg1: Array<Task>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTasks(arg0, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTasks(arg0, to_candid_vec_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateToDoItem(arg0: ToDoAuthRequest, arg1: ToDoItemUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateToDoItem(arg0, to_candid_ToDoItemUpdate_n92(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateToDoItem(arg0, to_candid_ToDoItemUpdate_n92(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Client_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardTasksResponse_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardTasksResponse): DashboardTasksResponse {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_DateSearchResult_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DateSearchResult): DateSearchResult {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_DueDateModalResponse_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DueDateModalResponse): DueDateModalResponse {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_DueDateTaskDetails_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DueDateTaskDetails): DueDateTaskDetails {
    return from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_PublicClient_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicClient): PublicClient {
    return from_candid_record_n83(_uploadFile, _downloadFile, value);
}
function from_candid_PublicTaskByAssignee_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicTaskByAssignee): PublicTaskByAssignee {
    return from_candid_record_n89(_uploadFile, _downloadFile, value);
}
function from_candid_PublicTask_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicTask): PublicTask {
    return from_candid_record_n86(_uploadFile, _downloadFile, value);
}
function from_candid_RevenueModalResponse_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevenueModalResponse): RevenueModalResponse {
    return from_candid_record_n77(_uploadFile, _downloadFile, value);
}
function from_candid_RevenueTaskDetails_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevenueTaskDetails): RevenueTaskDetails {
    return from_candid_record_n80(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ToDoItem_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToDoItem): ToDoItem {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Type__2_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__2): Type__2 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Type__3_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__3): Type__3 {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Type__4_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__4): Type__4 {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DueDateModalResponse]): DueDateModalResponse | null {
    return value.length === 0 ? null : from_candid_DueDateModalResponse_n69(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    status: _Type__2;
    title: string;
    clientId: number;
    paymentStatus: _Type;
    subType: [] | [string];
    completionDate: [] | [_Time];
    assignedTo: Principal;
    clientName: string;
    assignmentDate: [] | [_Time];
    bill: [] | [string];
    advanceReceived: [] | [bigint];
    createdAt: _Time;
    recurring: _Type__1;
    dueDate: [] | [_Time];
    manualAssignmentDate: [] | [_Time];
    taskType: _Type__3;
    comment: [] | [string];
    outstandingAmount: [] | [bigint];
    captains: Array<Principal>;
    assignedName: string;
}): {
    id: number;
    status: Type__2;
    title: string;
    clientId: number;
    paymentStatus: Type;
    subType?: string;
    completionDate?: Time;
    assignedTo: Principal;
    clientName: string;
    assignmentDate?: Time;
    bill?: string;
    advanceReceived?: bigint;
    createdAt: Time;
    recurring: Type__1;
    dueDate?: Time;
    manualAssignmentDate?: Time;
    taskType: Type__3;
    comment?: string;
    outstandingAmount?: bigint;
    captains: Array<Principal>;
    assignedName: string;
} {
    return {
        id: value.id,
        status: from_candid_Type__2_n33(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        paymentStatus: from_candid_Type_n35(_uploadFile, _downloadFile, value.paymentStatus),
        subType: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.subType)),
        completionDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.completionDate)),
        assignedTo: value.assignedTo,
        clientName: value.clientName,
        assignmentDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.assignmentDate)),
        bill: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.bill)),
        advanceReceived: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.advanceReceived)),
        createdAt: value.createdAt,
        recurring: from_candid_Type__1_n39(_uploadFile, _downloadFile, value.recurring),
        dueDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.dueDate)),
        manualAssignmentDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.manualAssignmentDate)),
        taskType: from_candid_Type__3_n41(_uploadFile, _downloadFile, value.taskType),
        comment: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.comment)),
        outstandingAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.outstandingAmount)),
        captains: value.captains,
        assignedName: value.assignedName
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<_Task>;
    date: _Time;
}): {
    tasks: Array<Task>;
    date: Time;
} {
    return {
        tasks: from_candid_vec_n30(_uploadFile, _downloadFile, value.tasks),
        date: value.date
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    title: string;
    owner: _ToDoItemOwner;
    modifiedAt: _Time;
    createdAt: _Time;
    completed: boolean;
    dueDate: [] | [_Time];
    description: [] | [string];
}): {
    id: number;
    title: string;
    owner: ToDoItemOwner;
    modifiedAt: Time;
    createdAt: Time;
    completed: boolean;
    dueDate?: Time;
    description?: string;
} {
    return {
        id: value.id,
        title: value.title,
        owner: value.owner,
        modifiedAt: value.modifiedAt,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.dueDate)),
        description: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.description))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    pan: [] | [string];
    status: _Type__4;
    subCategory: [] | [string];
    contactInfo: string;
    name: string;
    recurring: _Type__1;
    gstin: [] | [string];
    taskCategory: _Type__3;
}): {
    id: number;
    pan?: string;
    status: Type__4;
    subCategory?: string;
    contactInfo: string;
    name: string;
    recurring: Type__1;
    gstin?: string;
    taskCategory: Type__3;
} {
    return {
        id: value.id,
        pan: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.pan)),
        status: from_candid_Type__4_n56(_uploadFile, _downloadFile, value.status),
        subCategory: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.subCategory)),
        contactInfo: value.contactInfo,
        name: value.name,
        recurring: from_candid_Type__1_n39(_uploadFile, _downloadFile, value.recurring),
        gstin: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.gstin)),
        taskCategory: from_candid_Type__3_n41(_uploadFile, _downloadFile, value.taskCategory)
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionDateSorted: Array<_Task>;
    dueDateSorted: Array<_Task>;
}): {
    completionDateSorted: Array<Task>;
    dueDateSorted: Array<Task>;
} {
    return {
        completionDateSorted: from_candid_vec_n30(_uploadFile, _downloadFile, value.completionDateSorted),
        dueDateSorted: from_candid_vec_n30(_uploadFile, _downloadFile, value.dueDateSorted)
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskCount: bigint;
    items: Array<_DueDateTaskDetails>;
}): {
    taskCount: bigint;
    items: Array<DueDateTaskDetails>;
} {
    return {
        taskCount: value.taskCount,
        items: from_candid_vec_n71(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Type__2;
    assignee: string;
    paymentStatus: _Type;
    clientName: string;
    dueDate: [] | [_Time];
    taskTitle: string;
    comments: [] | [string];
}): {
    status: Type__2;
    assignee: string;
    paymentStatus: Type;
    clientName: string;
    dueDate?: Time;
    taskTitle: string;
    comments?: string;
} {
    return {
        status: from_candid_Type__2_n33(_uploadFile, _downloadFile, value.status),
        assignee: value.assignee,
        paymentStatus: from_candid_Type_n35(_uploadFile, _downloadFile, value.paymentStatus),
        clientName: value.clientName,
        dueDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.dueDate)),
        taskTitle: value.taskTitle,
        comments: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.comments))
    };
}
function from_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalAmount: bigint;
    items: Array<_RevenueTaskDetails>;
}): {
    totalAmount: bigint;
    items: Array<RevenueTaskDetails>;
} {
    return {
        totalAmount: value.totalAmount,
        items: from_candid_vec_n78(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: _Type;
    clientName: string;
    bill: [] | [string];
    advanceReceived: [] | [bigint];
    taskName: string;
    outstandingAmount: [] | [bigint];
}): {
    paymentStatus: Type;
    clientName: string;
    bill?: string;
    advanceReceived?: bigint;
    taskName: string;
    outstandingAmount?: bigint;
} {
    return {
        paymentStatus: from_candid_Type_n35(_uploadFile, _downloadFile, value.paymentStatus),
        clientName: value.clientName,
        bill: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.bill)),
        advanceReceived: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.advanceReceived)),
        taskName: value.taskName,
        outstandingAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.outstandingAmount))
    };
}
function from_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Type__4;
    name: string;
}): {
    status: Type__4;
    name: string;
} {
    return {
        status: from_candid_Type__4_n56(_uploadFile, _downloadFile, value.status),
        name: value.name
    };
}
function from_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Type__2;
    title: string;
    paymentStatus: _Type;
    subType: [] | [string];
    completionDate: [] | [_Time];
    clientName: string;
    dueDate: [] | [_Time];
    taskType: _Type__3;
    comment: [] | [string];
    assignedDate: [] | [_Time];
    assignedName: string;
    taskSubType: _Type__3;
}): {
    status: Type__2;
    title: string;
    paymentStatus: Type;
    subType?: string;
    completionDate?: Time;
    clientName: string;
    dueDate?: Time;
    taskType: Type__3;
    comment?: string;
    assignedDate?: Time;
    assignedName: string;
    taskSubType: Type__3;
} {
    return {
        status: from_candid_Type__2_n33(_uploadFile, _downloadFile, value.status),
        title: value.title,
        paymentStatus: from_candid_Type_n35(_uploadFile, _downloadFile, value.paymentStatus),
        subType: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.subType)),
        completionDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.completionDate)),
        clientName: value.clientName,
        dueDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.dueDate)),
        taskType: from_candid_Type__3_n41(_uploadFile, _downloadFile, value.taskType),
        comment: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.comment)),
        assignedDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.assignedDate)),
        assignedName: value.assignedName,
        taskSubType: from_candid_Type__3_n41(_uploadFile, _downloadFile, value.taskSubType)
    };
}
function from_candid_record_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Type__2;
    title: string;
    paymentStatus: _Type;
    completionDate: [] | [_Time];
    clientName: string;
    dueDate: [] | [_Time];
    taskStatus: _Type__2;
    taskType: _Type__3;
    comment: [] | [string];
    assignedDate: [] | [_Time];
    assignedName: string;
    taskSubType: _Type__3;
}): {
    status: Type__2;
    title: string;
    paymentStatus: Type;
    completionDate?: Time;
    clientName: string;
    dueDate?: Time;
    taskStatus: Type__2;
    taskType: Type__3;
    comment?: string;
    assignedDate?: Time;
    assignedName: string;
    taskSubType: Type__3;
} {
    return {
        status: from_candid_Type__2_n33(_uploadFile, _downloadFile, value.status),
        title: value.title,
        paymentStatus: from_candid_Type_n35(_uploadFile, _downloadFile, value.paymentStatus),
        completionDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.completionDate)),
        clientName: value.clientName,
        dueDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.dueDate)),
        taskStatus: from_candid_Type__2_n33(_uploadFile, _downloadFile, value.taskStatus),
        taskType: from_candid_Type__3_n41(_uploadFile, _downloadFile, value.taskType),
        comment: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.comment)),
        assignedDate: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.assignedDate)),
        assignedName: value.assignedName,
        taskSubType: from_candid_Type__3_n41(_uploadFile, _downloadFile, value.taskSubType)
    };
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    hold: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    docsPending: null;
}): Type__2 {
    return "pending" in value ? Type__2.pending : "hold" in value ? Type__2.hold : "completed" in value ? Type__2.completed : "inProgress" in value ? Type__2.inProgress : "docsPending" in value ? Type__2.docsPending : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
}): Type {
    return "pending" in value ? Type.pending : "paid" in value ? Type.paid : "overdue" in value ? Type.overdue : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    none: null;
} | {
    quarterly: null;
} | {
    monthly: null;
} | {
    yearly: null;
}): Type__1 {
    return "none" in value ? Type__1.none : "quarterly" in value ? Type__1.quarterly : "monthly" in value ? Type__1.monthly : "yearly" in value ? Type__1.yearly : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    GST: null;
} | {
    TDS: null;
} | {
    ITNotice: null;
} | {
    Accounts: null;
} | {
    Audit: null;
} | {
    Other: null;
} | {
    FormFiling: null;
} | {
    CACertificate: null;
}): Type__3 {
    return "GST" in value ? Type__3.GST : "TDS" in value ? Type__3.TDS : "ITNotice" in value ? Type__3.ITNotice : "Accounts" in value ? Type__3.Accounts : "Audit" in value ? Type__3.Audit : "Other" in value ? Type__3.Other : "FormFiling" in value ? Type__3.FormFiling : "CACertificate" in value ? Type__3.CACertificate : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): Type__4 {
    return "active" in value ? Type__4.active : "inactive" in value ? Type__4.inactive : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToDoItem>): Array<ToDoItem> {
    return value.map((x)=>from_candid_ToDoItem_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DueDateTaskDetails>): Array<DueDateTaskDetails> {
    return value.map((x)=>from_candid_DueDateTaskDetails_n72(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RevenueTaskDetails>): Array<RevenueTaskDetails> {
    return value.map((x)=>from_candid_RevenueTaskDetails_n79(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicClient>): Array<PublicClient> {
    return value.map((x)=>from_candid_PublicClient_n82(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicTask>): Array<PublicTask> {
    return value.map((x)=>from_candid_PublicTask_n85(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicTaskByAssignee>): Array<PublicTaskByAssignee> {
    return value.map((x)=>from_candid_PublicTaskByAssignee_n88(_uploadFile, _downloadFile, x));
}
function to_candid_Client_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Client): _Client {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_DashboardTasksRequest_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DashboardTasksRequest): _DashboardTasksRequest {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_DueDateDayType_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DueDateDayType): _DueDateDayType {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_RevenueCardType_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RevenueCardType): _RevenueCardType {
    return to_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function to_candid_SortDirection_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortDirection): _SortDirection {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_TaskFilter_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskFilter): _TaskFilter {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ToDoFilterType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDoFilterType): _ToDoFilterType {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_ToDoItemCreate_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDoItemCreate): _ToDoItemCreate {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ToDoItemUpdate_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDoItemUpdate): _ToDoItemUpdate {
    return to_candid_record_n93(_uploadFile, _downloadFile, value);
}
function to_candid_Type__1_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): _Type__1 {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Type__2_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): _Type__2 {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Type__3_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__3): _Type__3 {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Type__4_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__4): _Type__4 {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DueDateDayType | null): [] | [_DueDateDayType] {
    return value === null ? candid_none() : candid_some(to_candid_DueDateDayType_n65(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    pan?: string;
    status: Type__4;
    subCategory?: string;
    contactInfo: string;
    name: string;
    recurring: Type__1;
    gstin?: string;
    taskCategory: Type__3;
}): {
    id: number;
    pan: [] | [string];
    status: _Type__4;
    subCategory: [] | [string];
    contactInfo: string;
    name: string;
    recurring: _Type__1;
    gstin: [] | [string];
    taskCategory: _Type__3;
} {
    return {
        id: value.id,
        pan: value.pan ? candid_some(value.pan) : candid_none(),
        status: to_candid_Type__4_n11(_uploadFile, _downloadFile, value.status),
        subCategory: value.subCategory ? candid_some(value.subCategory) : candid_none(),
        contactInfo: value.contactInfo,
        name: value.name,
        recurring: to_candid_Type__1_n13(_uploadFile, _downloadFile, value.recurring),
        gstin: value.gstin ? candid_some(value.gstin) : candid_none(),
        taskCategory: to_candid_Type__3_n15(_uploadFile, _downloadFile, value.taskCategory)
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    dueDate?: Time;
    description?: string;
}): {
    title: string;
    dueDate: [] | [_Time];
    description: [] | [string];
} {
    return {
        title: value.title,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    status: Type__2;
    title: string;
    clientId: number;
    paymentStatus: Type;
    subType?: string;
    completionDate?: Time;
    assignedTo: Principal;
    clientName: string;
    assignmentDate?: Time;
    bill?: string;
    advanceReceived?: bigint;
    createdAt: Time;
    recurring: Type__1;
    dueDate?: Time;
    manualAssignmentDate?: Time;
    taskType: Type__3;
    comment?: string;
    outstandingAmount?: bigint;
    captains: Array<Principal>;
    assignedName: string;
}): {
    id: number;
    status: _Type__2;
    title: string;
    clientId: number;
    paymentStatus: _Type;
    subType: [] | [string];
    completionDate: [] | [_Time];
    assignedTo: Principal;
    clientName: string;
    assignmentDate: [] | [_Time];
    bill: [] | [string];
    advanceReceived: [] | [bigint];
    createdAt: _Time;
    recurring: _Type__1;
    dueDate: [] | [_Time];
    manualAssignmentDate: [] | [_Time];
    taskType: _Type__3;
    comment: [] | [string];
    outstandingAmount: [] | [bigint];
    captains: Array<Principal>;
    assignedName: string;
} {
    return {
        id: value.id,
        status: to_candid_Type__2_n24(_uploadFile, _downloadFile, value.status),
        title: value.title,
        clientId: value.clientId,
        paymentStatus: to_candid_Type_n26(_uploadFile, _downloadFile, value.paymentStatus),
        subType: value.subType ? candid_some(value.subType) : candid_none(),
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        assignedTo: value.assignedTo,
        clientName: value.clientName,
        assignmentDate: value.assignmentDate ? candid_some(value.assignmentDate) : candid_none(),
        bill: value.bill ? candid_some(value.bill) : candid_none(),
        advanceReceived: value.advanceReceived ? candid_some(value.advanceReceived) : candid_none(),
        createdAt: value.createdAt,
        recurring: to_candid_Type__1_n13(_uploadFile, _downloadFile, value.recurring),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        manualAssignmentDate: value.manualAssignmentDate ? candid_some(value.manualAssignmentDate) : candid_none(),
        taskType: to_candid_Type__3_n15(_uploadFile, _downloadFile, value.taskType),
        comment: value.comment ? candid_some(value.comment) : candid_none(),
        outstandingAmount: value.outstandingAmount ? candid_some(value.outstandingAmount) : candid_none(),
        captains: value.captains,
        assignedName: value.assignedName
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: Type__2;
    paymentStatus?: Type;
    subType?: string;
    assigneeName?: string;
    searchTerm?: string;
    taskType?: Type__3;
    comment?: string;
}): {
    status: [] | [_Type__2];
    paymentStatus: [] | [_Type];
    subType: [] | [string];
    assigneeName: [] | [string];
    searchTerm: [] | [string];
    taskType: [] | [_Type__3];
    comment: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_Type__2_n24(_uploadFile, _downloadFile, value.status)) : candid_none(),
        paymentStatus: value.paymentStatus ? candid_some(to_candid_Type_n26(_uploadFile, _downloadFile, value.paymentStatus)) : candid_none(),
        subType: value.subType ? candid_some(value.subType) : candid_none(),
        assigneeName: value.assigneeName ? candid_some(value.assigneeName) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        taskType: value.taskType ? candid_some(to_candid_Type__3_n15(_uploadFile, _downloadFile, value.taskType)) : candid_none(),
        comment: value.comment ? candid_some(value.comment) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionDateSortDirection: SortDirection;
    dueDateSortDirection: SortDirection;
}): {
    completionDateSortDirection: _SortDirection;
    dueDateSortDirection: _SortDirection;
} {
    return {
        completionDateSortDirection: to_candid_SortDirection_n60(_uploadFile, _downloadFile, value.completionDateSortDirection),
        dueDateSortDirection: to_candid_SortDirection_n60(_uploadFile, _downloadFile, value.dueDateSortDirection)
    };
}
function to_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    completed: boolean;
    dueDate?: Time;
    description?: string;
}): {
    title: string;
    completed: boolean;
    dueDate: [] | [_Time];
    description: [] | [string];
} {
    return {
        title: value.title,
        completed: value.completed,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__4): {
    active: null;
} | {
    inactive: null;
} {
    return value == Type__4.active ? {
        active: null
    } : value == Type__4.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    none: null;
} | {
    quarterly: null;
} | {
    monthly: null;
} | {
    yearly: null;
} {
    return value == Type__1.none ? {
        none: null
    } : value == Type__1.quarterly ? {
        quarterly: null
    } : value == Type__1.monthly ? {
        monthly: null
    } : value == Type__1.yearly ? {
        yearly: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__3): {
    GST: null;
} | {
    TDS: null;
} | {
    ITNotice: null;
} | {
    Accounts: null;
} | {
    Audit: null;
} | {
    Other: null;
} | {
    FormFiling: null;
} | {
    CACertificate: null;
} {
    return value == Type__3.GST ? {
        GST: null
    } : value == Type__3.TDS ? {
        TDS: null
    } : value == Type__3.ITNotice ? {
        ITNotice: null
    } : value == Type__3.Accounts ? {
        Accounts: null
    } : value == Type__3.Audit ? {
        Audit: null
    } : value == Type__3.Other ? {
        Other: null
    } : value == Type__3.FormFiling ? {
        FormFiling: null
    } : value == Type__3.CACertificate ? {
        CACertificate: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): {
    pending: null;
} | {
    hold: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    docsPending: null;
} {
    return value == Type__2.pending ? {
        pending: null
    } : value == Type__2.hold ? {
        hold: null
    } : value == Type__2.completed ? {
        completed: null
    } : value == Type__2.inProgress ? {
        inProgress: null
    } : value == Type__2.docsPending ? {
        docsPending: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
} {
    return value == Type.pending ? {
        pending: null
    } : value == Type.paid ? {
        paid: null
    } : value == Type.overdue ? {
        overdue: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToDoFilterType): {
    all: null;
} | {
    today: null;
} {
    return value == ToDoFilterType.all ? {
        all: null
    } : value == ToDoFilterType.today ? {
        today: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortDirection): {
    asc: null;
} | {
    desc: null;
} {
    return value == SortDirection.asc ? {
        asc: null
    } : value == SortDirection.desc ? {
        desc: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "dueTomorrow";
    dueTomorrow: null;
} | {
    __kind__: "dueToday";
    dueToday: null;
} | {
    __kind__: "anyDate";
    anyDate: null;
} | {
    __kind__: "customDate";
    customDate: Time;
}): {
    dueTomorrow: null;
} | {
    dueToday: null;
} | {
    anyDate: null;
} | {
    customDate: _Time;
} {
    return value.__kind__ === "dueTomorrow" ? {
        dueTomorrow: value.dueTomorrow
    } : value.__kind__ === "dueToday" ? {
        dueToday: value.dueToday
    } : value.__kind__ === "anyDate" ? {
        anyDate: value.anyDate
    } : value.__kind__ === "customDate" ? {
        customDate: value.customDate
    } : value;
}
function to_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RevenueCardType): {
    totalCollected: null;
} | {
    totalOutstanding: null;
} | {
    totalRevenue: null;
} {
    return value == RevenueCardType.totalCollected ? {
        totalCollected: null
    } : value == RevenueCardType.totalOutstanding ? {
        totalOutstanding: null
    } : value == RevenueCardType.totalRevenue ? {
        totalRevenue: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Task>): Array<_Task> {
    return value.map((x)=>to_candid_Task_n22(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Client>): Array<_Client> {
    return value.map((x)=>to_candid_Client_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
